# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Credit update untuk backpressure
class CreditUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreditUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreditUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CreditUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Credits to add (positive) or remove (negative)
    # CreditUpdate
    def CreditDelta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Current total credits available
    # CreditUpdate
    def TotalCredits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CreditUpdateStart(builder): builder.StartObject(2)
def Start(builder):
    return CreditUpdateStart(builder)
def CreditUpdateAddCreditDelta(builder, creditDelta): builder.PrependInt32Slot(0, creditDelta, 0)
def AddCreditDelta(builder, creditDelta):
    return CreditUpdateAddCreditDelta(builder, creditDelta)
def CreditUpdateAddTotalCredits(builder, totalCredits): builder.PrependUint32Slot(1, totalCredits, 0)
def AddTotalCredits(builder, totalCredits):
    return CreditUpdateAddTotalCredits(builder, totalCredits)
def CreditUpdateEnd(builder): return builder.EndObject()
def End(builder):
    return CreditUpdateEnd(builder)