# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Response dari connector
class ExecuteResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExecuteResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExecuteResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExecuteResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request ID yang sama dengan request
    # ExecuteResponse
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Success atau error
    # ExecuteResponse
    def ErrorClass(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Error message jika gagal
    # ExecuteResponse
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response payload jika sukses
    # ExecuteResponse
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ExecuteResponse
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ExecuteResponse
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecuteResponse
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Execution duration (microseconds)
    # ExecuteResponse
    def DurationUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ExecuteResponseStart(builder): builder.StartObject(5)
def Start(builder):
    return ExecuteResponseStart(builder)
def ExecuteResponseAddRequestId(builder, requestId): builder.PrependUint64Slot(0, requestId, 0)
def AddRequestId(builder, requestId):
    return ExecuteResponseAddRequestId(builder, requestId)
def ExecuteResponseAddErrorClass(builder, errorClass): builder.PrependInt8Slot(1, errorClass, 0)
def AddErrorClass(builder, errorClass):
    return ExecuteResponseAddErrorClass(builder, errorClass)
def ExecuteResponseAddErrorMessage(builder, errorMessage): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)
def AddErrorMessage(builder, errorMessage):
    return ExecuteResponseAddErrorMessage(builder, errorMessage)
def ExecuteResponseAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def AddPayload(builder, payload):
    return ExecuteResponseAddPayload(builder, payload)
def ExecuteResponseStartPayloadVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartPayloadVector(builder, numElems):
    return ExecuteResponseStartPayloadVector(builder, numElems)
def ExecuteResponseAddDurationUs(builder, durationUs): builder.PrependUint64Slot(4, durationUs, 0)
def AddDurationUs(builder, durationUs):
    return ExecuteResponseAddDurationUs(builder, durationUs)
def ExecuteResponseEnd(builder): return builder.EndObject()
def End(builder):
    return ExecuteResponseEnd(builder)