# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Request untuk eksekusi operasi connector
class ExecuteRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExecuteRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExecuteRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExecuteRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Unique request ID untuk correlation
    # ExecuteRequest
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Tenant ID (for multi-tenancy)
    # ExecuteRequest
    def TenantId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Workspace ID (optional)
    # ExecuteRequest
    def WorkspaceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Trace ID untuk distributed tracing
    # ExecuteRequest
    def TraceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Connector name (e.g., "http", "postgres")
    # ExecuteRequest
    def ConnectorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Operation name (e.g., "request", "query")
    # ExecuteRequest
    def Operation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Deadline absolute timestamp (milliseconds)
    # ExecuteRequest
    def DeadlineAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Payload data (operation-specific)
    # ExecuteRequest
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ExecuteRequest
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ExecuteRequest
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecuteRequest
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Optional headers/metadata
    # ExecuteRequest
    def Headers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Vastar.Connector.Ipc.KeyValue import KeyValue
            obj = KeyValue()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExecuteRequest
    def HeadersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecuteRequest
    def HeadersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def ExecuteRequestStart(builder): builder.StartObject(9)
def Start(builder):
    return ExecuteRequestStart(builder)
def ExecuteRequestAddRequestId(builder, requestId): builder.PrependUint64Slot(0, requestId, 0)
def AddRequestId(builder, requestId):
    return ExecuteRequestAddRequestId(builder, requestId)
def ExecuteRequestAddTenantId(builder, tenantId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tenantId), 0)
def AddTenantId(builder, tenantId):
    return ExecuteRequestAddTenantId(builder, tenantId)
def ExecuteRequestAddWorkspaceId(builder, workspaceId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(workspaceId), 0)
def AddWorkspaceId(builder, workspaceId):
    return ExecuteRequestAddWorkspaceId(builder, workspaceId)
def ExecuteRequestAddTraceId(builder, traceId): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)
def AddTraceId(builder, traceId):
    return ExecuteRequestAddTraceId(builder, traceId)
def ExecuteRequestAddConnectorName(builder, connectorName): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(connectorName), 0)
def AddConnectorName(builder, connectorName):
    return ExecuteRequestAddConnectorName(builder, connectorName)
def ExecuteRequestAddOperation(builder, operation): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(operation), 0)
def AddOperation(builder, operation):
    return ExecuteRequestAddOperation(builder, operation)
def ExecuteRequestAddDeadlineAtMs(builder, deadlineAtMs): builder.PrependUint64Slot(6, deadlineAtMs, 0)
def AddDeadlineAtMs(builder, deadlineAtMs):
    return ExecuteRequestAddDeadlineAtMs(builder, deadlineAtMs)
def ExecuteRequestAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def AddPayload(builder, payload):
    return ExecuteRequestAddPayload(builder, payload)
def ExecuteRequestStartPayloadVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartPayloadVector(builder, numElems):
    return ExecuteRequestStartPayloadVector(builder, numElems)
def ExecuteRequestAddHeaders(builder, headers): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(headers), 0)
def AddHeaders(builder, headers):
    return ExecuteRequestAddHeaders(builder, headers)
def ExecuteRequestStartHeadersVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartHeadersVector(builder, numElems):
    return ExecuteRequestStartHeadersVector(builder, numElems)
def ExecuteRequestEnd(builder): return builder.EndObject()
def End(builder):
    return ExecuteRequestEnd(builder)