# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Health check response
class HealthCheckResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HealthCheckResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealthCheckResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HealthCheckResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Is healthy
    # HealthCheckResponse
    def Healthy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Status message
    # HealthCheckResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Current active requests
    # HealthCheckResponse
    def ActiveRequests(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Available credits
    # HealthCheckResponse
    def AvailableCredits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HealthCheckResponseStart(builder): builder.StartObject(4)
def Start(builder):
    return HealthCheckResponseStart(builder)
def HealthCheckResponseAddHealthy(builder, healthy): builder.PrependBoolSlot(0, healthy, 0)
def AddHealthy(builder, healthy):
    return HealthCheckResponseAddHealthy(builder, healthy)
def HealthCheckResponseAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return HealthCheckResponseAddMessage(builder, message)
def HealthCheckResponseAddActiveRequests(builder, activeRequests): builder.PrependUint32Slot(2, activeRequests, 0)
def AddActiveRequests(builder, activeRequests):
    return HealthCheckResponseAddActiveRequests(builder, activeRequests)
def HealthCheckResponseAddAvailableCredits(builder, availableCredits): builder.PrependUint32Slot(3, availableCredits, 0)
def AddAvailableCredits(builder, availableCredits):
    return HealthCheckResponseAddAvailableCredits(builder, availableCredits)
def HealthCheckResponseEnd(builder): return builder.EndObject()
def End(builder):
    return HealthCheckResponseEnd(builder)