# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ipc

# Message type untuk frame header
class MessageType(object):
    # Execute operation request
    ExecuteRequest = 0
    # Execute operation response
    ExecuteResponse = 1
    # Health check ping
    HealthCheck = 2
    # Health check response
    HealthResponse = 3
    # Credit update (backpressure)
    CreditUpdate = 4
